# Generated by Django 2.1.7 on 2019-07-25 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0002_club_ligue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='ligue',
            field=models.CharField(choices=[('LG', 'Laliga'), ('BL', 'Barclays'), ('BG', 'Bundesliga'), ('SR', 'Seria'), ('BP', 'Bpl')], default='LG', max_length=2),
        ),
    ]
