# Generated by Django 2.1.7 on 2019-07-25 18:33

import clubs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0005_auto_20190726_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='club',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=clubs.models.upload_image_path),
        ),
    ]
