# Generated by Django 2.1.7 on 2019-07-28 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clubs', '0006_auto_20190726_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
