# Generated by Django 2.1.7 on 2019-07-25 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_player_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='featured',
            field=models.BooleanField(default=True),
        ),
    ]
