# Generated by Django 2.1.7 on 2019-07-29 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_auto_20190729_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
